# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new3.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1030, 656)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 50, 651, 541))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.video_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.video_label.setObjectName("video_label")
        self.verticalLayout.addWidget(self.video_label)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 600, 651, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.play_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.play_btn.setObjectName("play_btn")
        self.horizontalLayout.addWidget(self.play_btn)
        self.info_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.info_btn.setObjectName("info_btn")
        self.horizontalLayout.addWidget(self.info_btn)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(670, 50, 331, 191))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.puck_position_label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.puck_position_label.setMinimumSize(QtCore.QSize(111, 0))
        self.puck_position_label.setObjectName("puck_position_label")
        self.horizontalLayout_2.addWidget(self.puck_position_label)
        self.new_puck_position_label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.new_puck_position_label.setText("")
        self.new_puck_position_label.setObjectName("new_puck_position_label")
        self.horizontalLayout_2.addWidget(self.new_puck_position_label)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(670, 260, 331, 201))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.barcode_label = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.barcode_label.setEnabled(True)
        self.barcode_label.setMinimumSize(QtCore.QSize(111, 100))
        self.barcode_label.setObjectName("barcode_label")
        self.horizontalLayout_3.addWidget(self.barcode_label)
        self.barcode_text = QtWidgets.QTextEdit(self.horizontalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.barcode_text.sizePolicy().hasHeightForWidth())
        self.barcode_text.setSizePolicy(sizePolicy)
        self.barcode_text.setMaximumSize(QtCore.QSize(200, 150))
        self.barcode_text.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.barcode_text.setObjectName("barcode_text")
        self.horizontalLayout_3.addWidget(self.barcode_text)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(670, 480, 331, 111))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.reset_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reset_btn.sizePolicy().hasHeightForWidth())
        self.reset_btn.setSizePolicy(sizePolicy)
        self.reset_btn.setMinimumSize(QtCore.QSize(60, 60))
        self.reset_btn.setObjectName("reset_btn")
        self.horizontalLayout_4.addWidget(self.reset_btn)
        self.save_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_btn.sizePolicy().hasHeightForWidth())
        self.save_btn.setSizePolicy(sizePolicy)
        self.save_btn.setMinimumSize(QtCore.QSize(150, 100))
        self.save_btn.setObjectName("save_btn")
        self.horizontalLayout_4.addWidget(self.save_btn)
        self.notice_label = QtWidgets.QLabel(self.centralwidget)
        self.notice_label.setGeometry(QtCore.QRect(10, 10, 991, 31))
        self.notice_label.setText("")
        self.notice_label.setObjectName("notice_label")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(670, 600, 331, 41))
        self.widget.setObjectName("widget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.set_backgroun_btn = QtWidgets.QPushButton(self.widget)
        self.set_backgroun_btn.setObjectName("set_backgroun_btn")
        self.horizontalLayout_5.addWidget(self.set_backgroun_btn)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PuckAutoLoader"))
        self.video_label.setText(_translate("MainWindow", "video"))
        self.play_btn.setText(_translate("MainWindow", "Stop"))
        self.info_btn.setText(_translate("MainWindow", "Info"))
        self.puck_position_label.setText(_translate("MainWindow", "Puck : "))
        self.barcode_label.setText(_translate("MainWindow", "Barcode: "))
        self.reset_btn.setText(_translate("MainWindow", "Reset"))
        self.save_btn.setText(_translate("MainWindow", "Save"))
        self.set_backgroun_btn.setText(_translate("MainWindow", "Set BackGround"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

